# Generated by Django 4.2 on 2023-05-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
