# Generated by Django 4.2 on 2023-05-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0004_collection_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinename', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='items-img')),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='info',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
