# Generated by Django 4.2 on 2023-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0005_electronics_alter_collection_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='option-img/')),
                ('info', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
