# Generated by Django 4.2 on 2023-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0006_fashion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='image',
            field=models.ImageField(null=True, upload_to='details-img/'),
        ),
    ]
