# Generated by Django 4.2 on 2023-05-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_alter_fashion_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fashion',
        ),
    ]
