# Generated by Django 4.2 on 2023-05-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detailinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('subjects', models.CharField(max_length=20)),
            ],
        ),
    ]
