# Generated by Django 4.2 on 2023-05-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=340)),
                ('email', models.EmailField(max_length=349)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
