# Generated by Django 4.1.7 on 2023-04-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleint',
            name='text',
            field=models.CharField(default=5, max_length=450),
            preserve_default=False,
        ),
    ]
